name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "20.8.1"
      - run: npm install -g @angular/cli
      - run: npm ci
      - run: npm ci
        working-directory: ./projects/ngx-resgrid-apps-shared
      - run: ng build ngx-resgridlib --configuration production
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
